### ISSUE TITLE
Toolbar gets cut off when selecting characters toward the edge

### ISSUE THREAD

**Issue by stev3reed** [globocom/megadraft#143]
![image](https://cloud.githubusercontent.com/assets/7061659/23923631/5afe1642-08d5-11e7-9823-3c8563994759.png)

I saw some issues related to toolbar positioning and edge characters, but is this a known issue as well? If I select a character or word on the very edge, the toolbar will appear in the middle but only if it isn't the first character or word of a first line. If it is the first line, it will appear off-screen or if it is a single character or more in from the very edge then it will appear right over the insertion point which will cause the toolbar to be cut off if you are near the edge.

**Comment by cameackeSEL** [comment]
Same as this right? https://github.com/globocom/megadraft/issues/111

**Comment by stev3reed** [comment]
I saw that one but it isn’t the same. That one mentions the toolbar appearing in the middle, whereas my issue deals with the toolbar actually appearing off-screen. They both live in the ballpark of positioning wonkiness though.

a, pre, code, a:link, body { word-wrap: break-word !important; }

**Comment by cameackeSEL** [comment]
@stev3reed yeah that was my bad, I didn't check the screenshot

**Comment by StevenIseki** [comment]
Just a note, I got around this in Last Draft which uses Megadraft's toolbar by having a `maxLeftOffset` prop which I passed through to `getSelectionCoords`

**Comment by stev3reed** [comment]
Awesome, thanks @StevenIseki we will give that a shot.

**Comment by huitre** [comment]
@stev3reed I've made a PR to fix this issue : #152 
Help me getting it merged : )

**Comment by devonJS** [comment]
Hey all! I might be getting something similar to this, initially when I highlight  text on the left side, the arrow correctly positions itself to the left of the editor bubble:

![screen shot 2017-08-18 at 12 01 20 pm](https://user-images.githubusercontent.com/10638459/29473646-6624788c-840d-11e7-83f3-4ccfa24b2962.png)

However, when I toggle around the Bold and Italic, the editor gets moved so that the arrow is now in the middle of the editor bubble:

![screen shot 2017-08-18 at 12 02 03 pm](https://user-images.githubusercontent.com/10638459/29473677-7e65f3f8-840d-11e7-94d2-0d1e15a0ae54.png)

Is there a way to keep the editor from re-positioning / re-rendering on Bold/Italic click?  I'm using v0.4.26.

**Comment by shahilpb** [comment]
please help me, which steps I need to follow?
