### ISSUE TITLE
Edge: Creating a Link from inline toolbar causes SCRIPT28: Out of stack space error

### ISSUE THREAD

**Issue by CameronAckermanSEL** [globocom/megadraft#157]
**Environment:** 
Microsoft Edge 38.14393.1066.0

**Expected Behavior:**
When creating links in megadraft via the inline toolbar, the toolbar is responsive and a link is created once the user submits a link.

**Observed:**
When clicking the link button in the toolbar, the web page will hang and eventually yield an error without opening the link input field.

![image](https://cloud.githubusercontent.com/assets/14242948/26005792/0494e66c-36ef-11e7-91f5-27a54ca96a86.png)

**Impact:**

Unable to create links in megadraft when using edge.

**Steps to reproduce:**

1. Highlight text on megadraft live demo
2. Click the link button on the inline toolbar
3. Observe that site hangs, and eventually error appears in devtools console.

**Comment by CameronAckermanSEL** [comment]
This does not happen in IE.

**Comment by remolueoend** [comment]
We noticed the same issue with Chrome (59.0.3071.115 and 60.0.3112.50 beta (64-Bit)), but not with Firefox.

What we observed so far:
`componentDidUpdate` of component [Toolbar](https://github.com/globocom/megadraft/blob/master/src/components/Toolbar.js) calls [`setBarPosition`](https://github.com/globocom/megadraft/blob/master/src/components/Toolbar.js#L105) to reposition the toolbar.
`setBarPosition` again calls `setState` if the return of [`utils.getSelectionCoords`](https://github.com/globocom/megadraft/blob/master/src/utils.js#L47) is different than during the previous call, which is the case for thousands of subsequent calls in Chrome. 

Looks like the calculation of the editor position using `getBoundingClientRect` and `getVisibleSelectionRect` yields different results in a very short time. Calling `setBarPosition` after a delay of a few milliseconds solved the issue.
Not sure if this kind of hack is worth a PR.

**Comment by raphasilvac** [comment]
Hello guys,

first of all, sorry about my english.

As mentioned by @remolueoend, I observed that problem happens because sometimes toolbar component getting in looping,
(componentDidUpdate > setBarPosition > setState > componentDidUpdate > componentDidUpdate > setBarPosition...)

It's happening because there is a 14px difference bettewen `this.state.position.bottom` and `selectionCoords.offsetBottom`

Example:

First loop:
`this.state.position.bottom = 100`
`selectionCoords.offsetBottom = 114`

second loop:
First loop:
`this.state.position.bottom = 114`
`selectionCoords.offsetBottom = 128`

I think that in the second loop it should have the same values (avoiding the loop)

In the utils.js getSelectionCoords, I removed the "14px" sum:
`const offsetBottom = editorBounds.bottom - rangeBounds.top + 14;`
to
`const offsetBottom = editorBounds.bottom - rangeBounds.top;`

That was fixed the problem but is not a good solution, because toolbar can get a wrong position (14px)

**Comment by tacoelho** [comment]
I´ve made some changes but I coundn´t test them because my notebook went dead. 
Could anyone check it please?
