### ISSUE TITLE
Selection state on media block

### ISSUE THREAD

**Issue by vierno** [globocom/megadraft#27]
Add visual feedback to media block selection.

![screen shot 2016-04-27 at 5 14 29 pm](https://cloud.githubusercontent.com/assets/681628/14866760/8cee01bc-0c9b-11e6-8aee-011badf6378a.png)

**Comment by rafaelfragosom** [comment]
I'll do it.

**Comment by marcelometal** [comment]
Hi @rafaelfragosom, Any news on that?

**Comment by rafaelfragosom** [comment]
@marcelometal 90% done. Sorry the delay.

**Comment by wdtamagi** [comment]
Hello guys, 
I started to work on this, but I have some questions:

This feature is only for image or need apply this to video to?

If you look to my PR, in some components I hand on only style property, would it be better to hand on all properties to be more generic?

@vierno

**Comment by wdtamagi** [comment]
Until now the selection state only apply when i focus on image, and lost focus when i focus on toolbar or description fields.

I make this because in the future can implement key events to the block, like delete if selected remove the block without conflict with descriptions fields on the bottom of block. Is this a valid way or would be better selection state on focus of any component inside block?

**Comment by wdtamagi** [comment]
@marcelometal

**Comment by wdtamagi** [comment]
@JeanPinzon Can you help with this questions?

**Comment by wdtamagi** [comment]
I will make a new PR.

**Comment by wdtamagi** [comment]
I'm waiting the merge of #262 for send my PR because the read-only state impact on selection state of image block.

**Comment by mogavin** [comment]
Hi @wdtamagi ! We re-analyzed this issue and, because we have change plans that will affect both the visual and structural aspects, we believe it would not fit right now. Anyway we appreciate your contribution and we ask you to follow our future roadmaps.
